name: mycloset-ai
channels:
  - conda-forge
  - pytorch
  - nvidia
dependencies:
  - python=3.9
  - numpy=1.24.3
  - scipy=1.11.4
  - opencv=4.8.1
  - pillow=10.1.0
  - scikit-image=0.22.0
  - pip
  - pip:
    - fastapi==0.104.1
    - uvicorn[standard]==0.24.0
    - python-multipart==0.0.6
    - pydantic==2.5.0
    - torch==2.1.0
    - torchvision==0.16.0
    - mediapipe==0.10.7
    - rembg==2.0.50